### ISSUE TITLE
No umlauts so far

### ISSUE THREAD

**Issue by ntry** [Laverlin/Yet-Another-WatchFace#1]
I am living in Germany and the typeface does not show any umlauts like äöü etc. My hometown is Lübeck and so I am often only seeing L□beck on the watch face. Maybe you can fix this, somehow

**Comment by Laverlin** [comment]
What version of the watch-face are you using? You may check this in the Garmin Connect mobile app -> the watch-face settings. 
The umlaut issue has been fixed for a long time ago, the last version of the watch-face is 0.9.239 and it should show "Lubeck" in your location.  
I can't show ü as custom font does not support it so I just remove umlauts, that's better than square, anyway.
