### ISSUE TITLE
BUILD: ERROR: Undefined symbol "WatchServerTokenValue" detected.

### ISSUE THREAD

**Issue by blackart0** [Laverlin/Yet-Another-WatchFace#10]
Eclipse Version: 2021-06 (4.20.0) ,Mac OSX 11.5.2, Garmin SDK 4.0.4 ,source code version 0.9.252
YetAnotherWatchFaceView.mc

`		Setting.SetWatchServerToken(Ui.loadResource(Rez.Strings.WatchServerTokenValue));
		Setting.SetExchangeApiKey(Ui.loadResource(Rez.Strings.ExchangeApiKeyValue));
		Setting.SetIsTest(Ui.loadResource(Rez.Strings.IsTest).toNumber() == 1);`
//----------------------------------------------------------------------

`BUILD: /Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.macosx.x86_64_16.0.1.v20210528-1205/jre/bin/java -Dfile.encoding=UTF-8 -Dapple.awt.UIElement=true -jar /Users/mac/Library/Application Support/Garmin/ConnectIQ/Sdks/connectiq-sdk-mac-4.0.4-2021-07-01-9df386fcd/bin/monkeybrains.jar -o /Users/mac/eclipse-workspace/Yet-Another-WatchFace-Release-0.9.252/bin/Yet-Another-WatchFace-Release-0.9.252.prg -w -y /Users/mac/Downloads/Gamin/garmin_developer_key -f /Users/mac/eclipse-workspace/Yet-Another-WatchFace-Release-0.9.252/monkey.jungle 

BUILD: ERROR: /Users/mac/eclipse-workspace/Yet-Another-WatchFace-Release-0.9.252/source/YetAnotherWatchFaceView.mc:46:  Undefined symbol "WatchServerTokenValue" detected.

BUILD: ERROR: /Users/mac/eclipse-workspace/Yet-Another-WatchFace-Release-
0.9.252/source/YetAnotherWatchFaceView.mc:47:  Undefined symbol "ExchangeApiKeyValue" detected.

BUILD: ERROR: /Users/mac/eclipse-workspace/Yet-Another-WatchFace-Release-0.9.252/source/YetAnotherWatchFaceView.mc:48:  Undefined symbol "IsTest" detected.

BUILD: Complete`
//----------------------------------------------------------------------

**Comment by wolfiex** [comment]
Duplicated results.
