### ISSUE TITLE
Moon phase issue and suggestion

### ISSUE THREAD

**Issue by bellostom** [Laverlin/Yet-Another-WatchFace#11]
Hi

First of all the watchface is awesome. Many thanks!!
I installed in on my Fenix 7 and it seems as if the moon phase is not working. It is displayed empty, while currently it seems to be at 4% for my location
https://www.timeanddate.com/astronomy/greece/ioannina

Also it would be great if you added air pressure value as an option in the data fields

Regards

**Comment by bellostom** [comment]
Hi again
An update regarding the moon phase. I plugged in the watch to the computer and opened Garmin express to check something in the maps. After I unplugged the watch, I saw that the moon phase was updated. 
Mentioning it in case it somehow helps

Thanks

**Comment by Laverlin** [comment]
It is not a bug, there is about a 5% error margin in moon phases. As for the moon phase update during the Garmin Express connection, it seems just a coincidence.
