### ISSUE TITLE
Weather update

### ISSUE THREAD

**Issue by Andeimian** [Laverlin/Yet-Another-WatchFace#16]
Will It be possible to update weather in less than 60min? It would be great to update It maybe once per 15 min.Thank you

**Comment by Laverlin** [comment]
I'm afraid it will drain the battery even faster. However, there is a small trick - you may enforce data update by quickly switching to another app and getting back to watchface. This will force the WF to update within 5 min.

**Comment by Andeimian** [comment]
Hi,

Thanks for your answer, I understand. But It will be nice to have at least
the option to push a button and get the weather refreshed/updated.

**Comment by Laverlin** [comment]
Unfortunatly, this is not technically possible with the current watch face API. The Garmin SDK does not provides the ability to interact with a user in a watchface app.

**Comment by Andeimian** [comment]
Thats a pitty!

Thanks for quick response
