### ISSUE TITLE
not an issue a question - how to configure through watchface

### ISSUE THREAD

**Issue by edystein** [Laverlin/Yet-Another-WatchFace#2]
Hi,
Very impressing app!
Writing my first watch-face for fun https://apps.garmin.com/en-US/apps/ab2187db-417d-4331-8409-94a2ca2e6701.

I did not find how to configure watch-face via the Garmin connect app.
Saw you did that in.
can you please point on code or how you do that.

Thanks
Edy

**Comment by Laverlin** [comment]
The documentation is here: https://developer.garmin.com/connect-iq/programmers-guide/resource-compiler/
You would scroll down to the "Settings" topic.
