### ISSUE TITLE
Currency symbols 

### ISSUE THREAD

**Issue by Mercerudy** [Laverlin/Yet-Another-WatchFace#4]
The exchange rate feature is pretty cool, but if BTC-USD is selected, it pushes the "usd" text off the right side of my watch screen, because the number is 5 digits, dec, 2 digits long.

Could we get an option to display the "$" or relevant currency symbol?

Thanks!

**Comment by Laverlin** [comment]
Fixed.
If the rate value is too long currency symbols will be displayed for usd, eur, jpy and rur
Thanks for the feedback.
