### ISSUE TITLE
Language characters

### ISSUE THREAD

**Issue by phillipkettle** [Laverlin/Yet-Another-WatchFace#7]
Thanks so much for the WatchFace I love IT! 

Will it be able to attach UTF8 encoding so I can get my special characters from Denmark. 
Maybe it also needs, im not an engineer I just know with subtitles you need UTF8 encoding
ISO 8859-1

Now my city name's looks like this for example
Drag□r

And with UTF8 it would look like
Dragør

**Comment by Laverlin** [comment]
Thanks! 
The thing is that Watches does not support Unicode characters. 
The watch fonts are raster-based (basically it is just a set of images), and to support the whole set of UTF-8 font characters would take too much memory.
As a workaround, I'm removing the diacritic characters on a server so for instance, "crème brûlée" becomes "creme brulee". Not perfect, but better than "cr[]me br[]l[]e"
Apparently, this does not work with ø. I'll try to find the workaround for this. Thanks for the feedback!

**Comment by phillipkettle** [comment]
> Thanks!
> The thing is that Watches does not support Unicode characters.
> The watch fonts are raster-based (basically it is just a set of images), and to support the whole set of UTF-8 font characters would take too much memory.
> As a workaround, I'm removing the diacritic characters on a server so for instance, "crème brûlée" becomes "creme brulee". Not perfect, but better than "cr[]me br[]l[]e"
> Apparently, this does not work with ø. I'll try to find the workaround for this. Thanks for the feedback!

Quick reply thanks man
Maybe you could do it so the following would swap the characters or will that also take up memory ? That is how you type if it you don't have a danish letters and type it. Just an example good work thank you :)
Ø = oe
Æ = ae
Å = aa

**Comment by Laverlin** [comment]
Fixed.
Please update the app, since version 0.9.252 non-ASCII characters in city name should be displayed correctly.
