### ISSUE TITLE
location services not working

### ISSUE THREAD

**Issue by basaandewiel** [Laverlin/Yet-Another-WatchFace#9]
I build your nice watchface, and it runs fine, except for all items that depend on location services (like cityname).
Both in the simulator and on my real watch (Fenix 6x Pro solar), I have set a location (on real watch by starting an activity and waiting for a GPS fix).

I also put in my bing key in the secrets.xml file.
I am new to making watch faces, but nowhere in your code I can find a call to the BING API.
Any help in getting the location based functions is welcome.

NB: when I install your watch face from the Connect IQ store, it works perfectly.

**Comment by Laverlin** [comment]
The watch face does not get the data directly from Bing. It gets them through a proxy server that optimizes requests and collects data from various online services, including Bing. You should have the key from the proxy server, or you may run the proxy on your own, the source code is also available.
